### ISSUE TITLE
Trying to adapt your code to Segments table

### ISSUE THREAD

**Issue by LaurentBerder** [isaacobezo/get_rita#5]
Hi,

I'm trying to use your code, and apply it to another table on RITA's website: https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=293&DB_Short_Name=Air%20Carriers

However, after the `local_file = urlretrieve(remote_file, zip_file_name)` line, `z = ZipFile(zip_file_name)` invariably returns `Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file`

I don't understand how the urlretrieve is supposed to save a file (especially without specifying a path).

**Comment by isaacobezo** [comment]
I think that the backend has changed so much since I wrote this that it would require a complete rewrite of this tool.
I am sorry this is taking a long time to fix. I am not sure when I will fix this though. Be wary of it.

**Comment by LaurentBerder** [comment]
I solved my problem by using a completely different approach with `selenium` package.

Now my program opens the webpage, selects the year, month and required fields, then clicks on "Download".

It's actually much simpler!

**Comment by LaurentBerder** [comment]
Here's [my code](https://github.com/LaurentBerder/Passengers_Prediction/blob/master/Download_segments_from_RITA.py) if you need to simplify yours in the future.
